version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bourbon
    versions:
    - "< 6, >= 5.a"
  - dependency-name: bourbon
    versions:
    - ">= 6.a, < 7"
  - dependency-name: bourbon
    versions:
    - ">= 7.a, < 8"
  - dependency-name: font-awesome-sass
    versions:
    - ">= 5.a, < 6"
  - dependency-name: middleman
    versions:
    - "< 5, >= 4.a"
