version: "3"
volumes:
  bundle: { driver: local }
  config: { driver: local }
services:
  app:
    image: alpinelab/ruby-dev
    command: ["middleman", "server", "--bind-address=0.0.0.0"]
    ports:
      - "4567:4567"
      - "35729:35729"
    volumes:
      - .:/app
      - bundle:/bundle
      - config:/config
